baseURL = 'https://anandsiva.com/'
languageCode = 'en-us'
title = 'Dr. Strangelog'
theme = "terminal"
[params]
  terminalPrompt = "dr@strangelog:~$"
[params.logo]
   logoText = "Dr. Strangelog"
   logoHomeLink = "/"
